Repository Waha-net/waha-net, pull requests merged in 2025-02, with the labels that each got.

#3 Implemented WahaApiClient and required entities
  src/Client/Client.csproj
  src/Client/IWahaApiClient.cs
  src/Client/WahaApiClient.cs
  src/Client/WahaApiClientBuilder.cs
  src/Client/WahaEntities.cs
  src/Client/WahaExtension.cs
  src/Client/WahaSettings.cs
  src/Waha.sln
Labels: enhancement

#6 Feature/client adjustments
  .github/workflows/dotnet.yml
  src/Client.csproj
  src/Client/Client.csproj
  src/IWahaApiClient.cs
  src/Waha.sln
  src/WahaApiClient.cs
  src/WahaApiClientBuilder.cs
  src/WahaEntities.cs
  src/WahaExtension.cs
  src/WahaSettings.cs
Labels: enhancement

#7 Update README.md
  README.md
Labels: documentation

#8 Update dotnet.yml
  .github/workflows/dotnet.yml
Labels: bug

#9 Update dotnet.yml
  .github/workflows/dotnet.yml
Labels: bug

#10 Update dotnet.yml
  .github/workflows/dotnet.yml
Labels: bug

#11 Update dotnet.yml
  .github/workflows/dotnet.yml
Labels: bug

#12 Update dotnet.yml
  .github/workflows/dotnet.yml
Labels: bug

#13 Update dotnet.yml
  .github/workflows/dotnet.yml
Labels: bug

#14 Update dotnet.yml
  .github/workflows/dotnet.yml
Labels: bug

#15 Update dotnet.yml
  .github/workflows/dotnet.yml
Labels: bug

#16 Update dotnet.yml
  .github/workflows/dotnet.yml
Labels: bug

#20 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#24 Docs/badges and teamplates improvments
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: documentation
